kate: homework 4 completed
eugene-okulik/python_monsters pull request #10
Opened 2023-05-23 21:29 UTC by katherinetishevich

2023-05-27 07:42 UTC, eugene-okulik requested changes
Осталось поправить ошибку невнимательности. Остальное всё идеально

2023-05-27 07:42 UTC, eugene-okulik commented on homework/katherine_tishevich/homework_4/collections_task.py
> +my_dict["dict"]["i am a tuple"] = 1
Тест на внимательность не пройден ))  

> добавьте элемент с ключом ('i am a tuple',) и любым значением

А ты выполнила задание:

> добавьте элемент с ключом 'i am a tuple' и любым значением

2023-05-27 07:42 UTC, eugene-okulik commented on homework/katherine_tishevich/homework_4/collections_task.py
> +print(my_dict["str"][len(my_dict["str"]) // 2:(len(my_dict["str"]) // 2) + 4])
:+1:

2023-05-28 12:56 UTC, katherinetishevich commented on homework/katherine_tishevich/homework_4/collections_task.py
> +my_dict["dict"]["i am a tuple"] = 1
спасибо, обновила

2023-06-01 05:28 UTC, eugene-okulik approved these changes

2023-06-01 05:28 UTC, merged